version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres
    volumes:
      - ./:/code:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8100 --reload
    ports:
      - 8100:8100
#    env_file:
#      - ./.env
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD={DB_PASSWORD}
      - DATABASE_NAME={DB_NAME}
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30

  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD={DB_PASSWORD}
      - POSTGRES_DB={DB_NAME}

    volumes:
      - postgres-db:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 5050:80
    depends_on:
      - postgres


volumes:
  postgres-db: